apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: {{ .Values.backend.image }}
        ports:
        - containerPort: {{ .Values.backend.port }}
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql:3306/{{ .Values.mysql.database }}
        - name: SPRING_DATASOURCE_USERNAME
          value: {{ .Values.mysql.user }}
        - name: SPRING_DATASOURCE_PASSWORD
          value: {{ .Values.mysql.userPassword }}
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: update
